repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: check-toml
          - id: end-of-file-fixer

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.1
      hooks:
          - id: ruff
            args: [--fix]

    - repo: https://github.com/astral-sh/uv-pre-commit
      rev: 0.5.8
      hooks:
        - id: uv-lock
